Dao5
antoniukivan/jv-internet-taxi pull request #3
Opened 2021-01-14 10:07 UTC by antoniukivan

2021-01-14 11:04 UTC, ivlytvynets requested changes

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +            }
don't forget to close statements and connections

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +                manufacturer.setId(resultSet.getLong(1));
```suggestion
                manufacturer.setId(resultSet.getObject("manufacturer_id", Long.class));
```

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +                + "AND (manufacturer_deleted = 'FALSE')";
```suggestion
                + "AND manufacturer_deleted = FALSE";
```

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +                return Optional.of(getManufacturer(resultSet));
same

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +            }
same

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +            }
same

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +        String query = "UPDATE manufacturers SET manufacturer_deleted = 'TRUE' "
same

2021-01-14 11:04 UTC, ivlytvynets commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +            updatedRows = preparedStatement.executeUpdate();
same

2021-01-14 11:41 UTC, ivlytvynets approved these changes

2021-01-14 15:21 UTC, RomanDubovskyi requested changes

2021-01-14 15:21 UTC, RomanDubovskyi commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +            PreparedStatement preparedStatement
move statement inside of try with resources block and it will be closed automatically as well

2021-01-14 15:21 UTC, RomanDubovskyi commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +            if (resultSet != null && resultSet.next()) {
```suggestion
            if (resultSet.next()) {
```
resultSet won't be null, it can just be empty, so this check is redundant

2021-01-14 15:21 UTC, RomanDubovskyi commented on src/main/java/mate/academy/dao/impl/CarDaoImpl.java
> +        Car oldValue = get(car.getId()).orElseThrow();
why have you change this ?

2021-01-14 15:21 UTC, RomanDubovskyi commented on src/main/java/mate/academy/dao/jdbc/ManufacturerJdbcDao.java
> +            if (resultSet != null && resultSet.next()) {
same here

2021-01-15 07:58 UTC, RomanDubovskyi approved these changes
LGTM

2021-01-17 17:16 UTC, merged