Dao9
antoniukivan/jv-internet-taxi pull request #7
Opened 2021-01-23 09:34 UTC by antoniukivan

2021-01-23 11:03 UTC, antoniukivan commented on src/main/java/mate/academy/web/filters/AuthenticationFilter.java
> +        }
if driver was deleted during the session

2021-01-23 11:24 UTC, YuraBondarenko approved these changes

2021-01-25 16:38 UTC, Sofasmile requested changes

2021-01-25 16:38 UTC, Sofasmile commented on src/main/java/mate/academy/web/filters/AuthenticationFilter.java
> +        if (url.equals("/login") || url.equals("/drivers/create")) {
щоб в майбутньому блок if не розростався краще винести юрлки в сет, який будемо ініціалізовувати в методі  init()
Тоді в блоці if в нас буде єдина умова:  `if(allowedUrls.contains(url))`

2021-01-25 16:38 UTC, Sofasmile commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +        throw new AuthenticationException("Incorrect login or password");
```suggestion
        Optional<Driver> driver = driverService.findByLogin(login);
        if (driver. isPresent() && driver.getPassword().equals(password)) {
            return driver;
        }
        throw new AuthenticationException("Incorrect login or password");
```

2021-01-25 16:38 UTC, Sofasmile commented on src/main/java/mate/academy/dao/jdbc/CarJdbcDaoImpl.java
> +                String password = driversResultSet.getObject("password", String.class);
тут паролі все ж таки краще не діставти, заради безпеки. Можеш створити ще один конструктор з 3-ма параметрами для Driver

2021-01-26 09:06 UTC, Sofasmile approved these changes

2021-01-26 09:06 UTC, Sofasmile commented on src/main/java/mate/academy/model/Driver.java
>          this.licenseNumber = licenseNumber;
```suggestion
        this(name, licenseNumber, login);
        this.password = password;
```

2021-01-26 09:20 UTC, merged